// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8UwbmIyUC0KWwPtg95Wflktb4sw23s4c',
    appId: '1:969524752939:web:67a1ee2f11dc623823306e',
    messagingSenderId: '969524752939',
    projectId: 'ult-whatsapp',
    authDomain: 'ult-whatsapp.firebaseapp.com',
    databaseURL: 'https://ult-whatsapp-default-rtdb.firebaseio.com',
    storageBucket: 'ult-whatsapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLMht_ZogUvPOtFxthzQGoUM_x29PNvs0',
    appId: '1:969524752939:android:a2b2d4792c723c2b23306e',
    messagingSenderId: '969524752939',
    projectId: 'ult-whatsapp',
    databaseURL: 'https://ult-whatsapp-default-rtdb.firebaseio.com',
    storageBucket: 'ult-whatsapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ6wM6T-7SDHV1PsbwQoIcVsXs_ghYcwE',
    appId: '1:969524752939:ios:6d7dfd11050b138023306e',
    messagingSenderId: '969524752939',
    projectId: 'ult-whatsapp',
    databaseURL: 'https://ult-whatsapp-default-rtdb.firebaseio.com',
    storageBucket: 'ult-whatsapp.appspot.com',
    iosBundleId: 'com.example.ultWhatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ6wM6T-7SDHV1PsbwQoIcVsXs_ghYcwE',
    appId: '1:969524752939:ios:8395229909fcf8a423306e',
    messagingSenderId: '969524752939',
    projectId: 'ult-whatsapp',
    databaseURL: 'https://ult-whatsapp-default-rtdb.firebaseio.com',
    storageBucket: 'ult-whatsapp.appspot.com',
    iosBundleId: 'com.example.ultWhatsapp.RunnerTests',
  );
}
